version: '3.8'

services:
  backend:
    build: .
    container_name: blog_backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
